name: Publish Release

on:
  workflow_dispatch: 

jobs:
  mi-connector-release:
    uses: arunans23/mi-connector-core/.github/workflows/publish-release.yml@workflow
    with:
      build-arg: "value"
